googlemaps/java-on-demand-rides-deliveries-stub-provider

- README.md
This adds to our 'readme' the error thrown when user hasn't filled the 'FE' configuration.
Happened to me a couple of times while working locally that I dismissed the changes to 'config.properties' and forgot to bring them back.
> docs: Update readme with error caused by no FE config

- README.md
- src/main/java/com/example/provider/TripServlet.java
This adds support for the provider to update the 'intermediateDestinationIndex' for a trip.
This enables multiwaypoint trips for our sample apps.
In a previous PR we added support for creating trips with 'intermediateDestinations'
https://github.com/googlemaps/java-on-demand-rides-deliveries-stub-provider/pull/8
> feat: Support for 'intermediateDestinations' on PUT

- src/main/java/com/example/provider/json/DateSerializer.java
- src/main/java/com/example/provider/json/GsonProvider.java
The `GET /token/:tokenType` endpoint currently returns tokens' creation and expiration timestamps as strings, such as "Feb 27, 2022, 8:15:50 PM". These lack the timezone and are thus not useful for token management. This PR makes the JSON serializer converts a Java `Date` object to a Unix timestamp instead of a string.
> feat: Serialize Date objects to Unix timestamps in JSON

- README.md
- src/main/java/com/example/provider/TokenServlet.java
Add the new endpoint `GET /token/:tokenType/:id`. The `GET /token/:tokenType` endpoint will be removed once the sample apps are updated to pass the trip/vehicle ID to the provider.
> feat: Accept trip ID/vehicle ID when creating auth token

- src/main/java/com/example/provider/json/SerializedLatLng.java
- src/main/java/com/example/provider/json/TripSerializer.java
The provider currently serializes `LatLng` objects, which are protobuf objects, using Gson directly. So it returns the latitude and longitude with an `_` suffix along with internal protobuf properties that are not relevant to the users, such as
```json
{
"latitude_": 37.7748999,
"longitude_": -122.4194,
"memoizedIsInitialized": -1,
"unknownFields": {
"fields": {},
"fieldsDescending": {}
},
"memoizedSize": -1,
"memoizedHashCode": 0
}
```
This PR makes the provider return the latitude and longitude without the `_` suffix. However, since the sample apps are still relying on the underscore, this PR also makes the provider return the latitude and longitude with `_` for backward compatibility. The `latitude_` and `longitude_` keys will be removed once all the sample apps are updated to use …
> fix: Fix LatLng JSON serialization

- src/main/webapp/WEB-INF/appengine-web.xml
- src/main/webapp/WEB-INF/web.xml
- src/main/webapp/static/index.html
- src/main/webapp/static/main.css
- src/main/webapp/static/main.js
feat: Add index.html with basic diagnostics
This creates a 'index.html' page which will be the default '/' for the server.
The page just indicates that the server has been started and tries to generate a token for a Driver/Consumer to make sure everything has been properly setup.
> feat: Add index.html with basic diagnostics

- src/main/java/com/example/provider/json/SerializedLatLng.java
- src/main/java/com/example/provider/json/TripSerializer.java
Now that all the sample apps (Java, Kotlin, Swift, and Objective-C) have been updated to use `latitude`/`longtitude` instead of `latitude_`/`longtitude_`, we can remove `latitude_`/`longtitude_` from the LatLng JSON.
> fix: Remove latitude_/longitude_ from LatLng JSON

- README.md
- src/main/java/com/example/provider/TripServlet.java
- src/main/java/com/example/provider/utils/TripUtils.java
Allows clients to specify the 'tripType' for a 'Trip' to create. 
This is part of the series to allow creation of 'Shared pool' trips.
> feat: Allow clients to specify 'tripType' for 'POST'

- README.md
- src/main/java/com/example/provider/VehicleServlet.java
- src/main/java/com/example/provider/json/SerializedVehicle.java
- src/main/java/com/example/provider/json/VehicleSerializer.java
- src/main/java/com/example/provider/utils/VehicleUtils.java
Allows clients so specify a list of 'supported trip types' and 'maximum vehicle capacity' during creation.
It also serializes the mentioned values 
This is part of the series to allow creating 'Shared pool' trips.
> feat: Allow settings supportedTripTypes/maximumCapacity for vehicle creation

- README.md
- src/main/java/com/example/provider/VehicleServlet.java
- src/main/java/com/example/provider/utils/ServletUtils.java
Adds a 'PUT' endpoint for 'Vehicle'.
This allows updating settings for a 'Vehicle' such as supported trip types, back to back enabled, and maximum capacity.
This is part of the series to support creation of 'Shared pool' trips.
> feat: Support updating 'Vehicle' entities

- src/main/java/com/example/provider/ServletState.java
- src/main/java/com/example/provider/TripMatcher.java
- src/main/java/com/example/provider/TripServlet.java
- src/main/java/com/example/provider/VehicleServlet.java
- src/main/java/com/example/provider/utils/TripUtils.java
feat: support ordering waypoints for Shared pooling
Supports ordering 'Vehicle' waypoints for 'Shared trips' to created 'Shared pools'.
For Trips/Vehicles that don't support 'SHARED' trips, the changes are backwards compatible and should still work.
> feat: support ordering waypoints for Shared pooling

- README.md
- src/main/java/com/example/provider/json/SerializationUtils.java
- src/main/java/com/example/provider/json/SerializedVehicle.java
- src/main/java/com/example/provider/json/TripSerializer.java
- src/main/java/com/example/provider/json/VehicleSerializer.java
- src/main/java/com/example/provider/json/Waypoint.java
- src/main/java/com/example/provider/utils/WaypointUtils.java
Enable serializing the list of waypoints for the Vehicle so clients can rely on it for state management. 
Currently, clients rely on 'Trip.waypoints' for state tracking but this will change as we integrate 'Shared pooling'.
> feat: serialize list of vehicle waypoints to client

- src/main/java/com/example/provider/ServletState.java
- src/main/java/com/example/provider/ServletStatePropertyChangeListener.java
- src/main/java/com/example/provider/TokenServlet.java
- src/main/java/com/example/provider/TripMatcher.java
- src/main/java/com/example/provider/TripServlet.java
- The 'Trip matching' mechanism relies on a queue to determine the next trip to match. Currently, the logic only tries to match the top/head of the queue and if match can't be done (Example: Vehicle doesn't support trip type), then the queue gets stuck. This fixes the problem by moving through the queue looking for matches.
- Removes a few unused variables/imports from different files
> fix: prevent trips pending match queue from getting stuck

- build.gradle
This version of Fleet Engine Auth Library fixes the issue where the provider stops working after one hour. Thanks @danielfbright for suggesting the solution.
> feat: Upgrade Fleet Engine Auth Library to 1.9.1

- src/main/java/com/example/provider/json/SerializedVehicle.java
- src/main/java/com/example/provider/json/VehicleSerializer.java
Added etaToFirstWaypoint field in SerializedVehicle and set it in VehicleSerializer.
This change was necessary in order to display the etaToFirstWaypoint of vehicles in the Expeditor Sample App.
> feat: Added etaToFirstWaypoint field in SerializedVehicle

- build.gradle
Remove reference to jcenter in `repositories` block in build.gradle file so it will compile. Also upgrade ppengine-gradle-plugin to 2.4.3 to be consistent with the official document.
> Remove deprecated jcenter in repositories.

- src/main/java/com/example/provider/ServletState.java
- src/main/java/com/example/provider/TripServlet.java
- src/main/java/com/example/provider/json/TripData.java
chore: clean up routeToken code from provider
The "RouteToken" functionality was not implemented completely when it was introduced and at this point it would be better to just clean up. Neither of the Android/iOS sample apps use this field.
> chore: clean up routeToken code from provider

- README.md
The project can't be run from a system where JVM Java is higher than 11. This indicates that and provides users a recommendation on how to set the right version.
> chore: update README.md for Java version update

- README.md
- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- src/main/java/com/example/provider/utils/ServletUtils.java
- src/main/webapp/WEB-INF/appengine-web.xml
Move to use Java 11 by default, and set CORS headers.
- Java 8 is deprecated.
- CORS headers needed when deploying to AppEngine.
- Update some minor library versions as needed.
- Update Gradle to use latest v6.
> build: Use Java 11 by default and set CORS headers.

- src/main/java/com/example/provider/TripMatcher.java
The previous implementation could lead to trips remaining unassigned when multiple vehicles were attempting to be assigned concurrently. This was due to the `removeTripPendingMatch` call being executed prematurely, potentially removing a trip from the pending state before a successful written to fleet engine.
This commit ensures that all requested trips are properly assigned to available drivers by moving the `removeTripPendingMatch` call after the trip update is confirmed. This guarantees that trips remain assignable until they are successfully matched.
Added debug logs to track trip assignment state transitions for easier debugging and monitoring.
Tested with 4 consumers/drivers.
> fix: Concurrent trip assignment could leave trips in an unassigned state
